---

- name: Configure NTP
  netapp.ontap.na_ontap_ntp:
    server_name: "{{ item['server'] }}"
    state: "{{ item['state'] }}"
    hostname: "{{ netapp_common_hostname }}"
    username: "{{ netapp_common_username }}"
    password: "{{ netapp_common_password }}"
    validate_certs: "{{ netapp_common_validate_certs | default(false) }}"
  loop: "{{ netapp_common_ntp_server }}"
